# Generated by Django 2.1.2 on 2018-11-13 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='bill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userId', models.CharField(max_length=255, verbose_name='用户名id')),
                ('money', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='金额(元/￥)')),
                ('billType', models.CharField(choices=[('1', '收入'), ('2', '支出')], default='1', max_length=4, verbose_name='收支，默认1为收入2为支出')),
                ('colsId', models.CharField(max_length=255, verbose_name='收支类型id')),
                ('mark', models.TextField(verbose_name='文本备注')),
                ('time', models.DateField(default='', verbose_name='收支时间')),
                ('finallydate', models.DateTimeField(auto_now=True, verbose_name='最后一次更改这笔账单的时间')),
            ],
        ),
        migrations.CreateModel(
            name='classify',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adate', models.DateTimeField(auto_now_add=True, verbose_name='添加时，追加当前添加时间')),
                ('userId', models.CharField(max_length=255, verbose_name='用户名id')),
                ('name', models.CharField(max_length=50, verbose_name='类目名称')),
                ('billType', models.CharField(choices=[('1', '收入'), ('2', '支出')], default='1', max_length=4, verbose_name='收支，默认1为收入2为支出')),
                ('mark', models.TextField(verbose_name='文本备注')),
                ('finallydate', models.DateTimeField(auto_now=True, verbose_name='最后一次更改的时间')),
            ],
        ),
        migrations.CreateModel(
            name='log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adate', models.DateTimeField(auto_now_add=True, verbose_name='添加时，追加当前添加时间')),
                ('ip', models.CharField(max_length=255, verbose_name='记录导出的ip服务端与客户端的ip，用 ~ 分割')),
                ('condition', models.CharField(max_length=100, verbose_name='导出的条件，是以那个条件导出数据的')),
                ('userId', models.CharField(max_length=255, verbose_name='用户名id')),
            ],
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adate', models.DateTimeField(auto_now_add=True, verbose_name='添加时，追加当前添加时间/注册时间')),
                ('username', models.CharField(max_length=100, verbose_name='用户名称/账号')),
                ('password', models.CharField(max_length=100, verbose_name='用户密码')),
                ('sex', models.CharField(max_length=4, verbose_name='性别，默认1为男2为女')),
                ('addr', models.CharField(max_length=255, verbose_name='地址')),
                ('email', models.EmailField(max_length=254, verbose_name='邮箱')),
                ('wechat', models.CharField(max_length=100, verbose_name='微信号')),
                ('qq', models.CharField(max_length=100, verbose_name='qq号')),
                ('vip', models.SmallIntegerField(default=0, verbose_name='vip等级')),
                ('group', models.CharField(choices=[('1', '学生'), ('2', '农民'), ('3', '白领'), ('4', 'Boss'), ('5', '职工')], default=1, max_length=4, verbose_name='用户组')),
            ],
        ),
    ]
